import Head from "next/head";
import { Inter } from "@next/font/google";
import Navbar from "../components/Navbar";
import IndexImage from "../components/IndexImage";
import About from "../components/About";
import MyWork from "../components/MyWork";
import Contact from "../components/Contact";
import LoadInPage from "../components/LoadInPage";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Parker - Full-Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/PM.ico" />
      </Head>
      <main>
        <div>
          <LoadInPage />
          <Navbar />
          <IndexImage />
          <About />
          <MyWork />
          <Contact />
        </div>
      </main>
    </>
  );
}
